name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: t585585/idm-web-app:latest

  deploy_to_kubernetes:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image with tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: t585585/idm-web-app:${{ github.ref_name }}

      - name: Update Kubernetes deployment file with new image tag
        run: |
          sed -i 's|t585585/idm-web-app:.*|t585585/idm-web-app:${{ github.ref_name }}|' k8s/deploy-idm-web-app.yaml

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1

      - name: Configure Kubernetes credentials
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deploy-idm-web-app.yaml
